# Generated by Django 5.1.5 on 2025-01-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='number_of_books',
            field=models.IntegerField(default=224, max_length=int),
            preserve_default=False,
        ),
    ]
