# Generated by Django 5.1.5 on 2025-01-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddBooks',
            new_name='Books',
        ),
    ]
