# Generated by Django 5.1.5 on 2025-01-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0002_rename_addbooks_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
