# Generated by Django 5.1.5 on 2025-01-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
